### ISSUE TITLE
java.util.ConcurrentModificationException when concurrent requests to an endpoint is high

### ISSUE THREAD

**Issue by anwar-sadat** [resthub/springmvc-router#71]
threw exception [Request processing failed; nested exception is java.util.ConcurrentModificationException] with root cause
 java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
        at java.util.ArrayList$Itr.next(ArrayList.java:831)
        at org.resthub.web.springmvc.router.Router.route(Router.java:228)
        at org.resthub.web.springmvc.router.RouterHandlerMapping.getHandlerInternal(RouterHandlerMapping.java:168)
        at org.springframework.web.servlet.handler.AbstractHandlerMapping.getHandler(AbstractHandlerMapping.java:351)
        at org.springframework.web.servlet.DispatcherServlet.getHandler(DispatcherServlet.java:1120)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:932)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)

**Comment by anwar-sadat** [comment]
The exception is thrown when firing "50 requests in 10 seconds" 10 times. Simulated with JMeter
